version: "3.8"

services:
  root-config:
    build: ../root-config
    ports:
      - "9000:9000"
    volumes:
      - ../root-config:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  finance-app:
    build: ../finance-app
    ports:
      - "8080:8080"
    volumes:
      - ../finance-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
